In [5]:
import numpy as np
from scipy import linalg

# 행렬식(determinant) 구하는 식
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
print(np.linalg.det(a))
print(linalg.det(a))
s, md = np.linalg.slogdet(a)
print(np.linalg.slogdet(a))
print(s * np.exp(md))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-9.51619735393e-16
0.0
(-1.0, -34.588366156510311)
-9.51619735393e-16


In [4]:
# 여인수에 의한 행렬식 구해보기
import numpy as np

a = np.array([[3, 1, 3], [2, 2, 3], [1, 1, 1]])
print(a)
print(np.linalg.det(a))

s, md = np.linalg.slogdet(a)
print(np.linalg.slogdet(a))
print(s * np.exp(md))
m11 = np.linalg.det(a[1:, 1:])
m12 = np.linalg.det(a[1:, (0, 2)])
m13 = np.linalg.det(a[1:, (0, 1)])
print(a[1:, 1:])
print(m11)
print(a[1:, (0, 2)])
print(m12)
print(a[1:, (0, 1)])
print(m13)
print(m11 * a[0, 0] - m12 * a[0, 1] + m13 * a[0, 2])

[[3 1 3]
 [2 2 3]
 [1 1 1]]
-2.0
(-1.0, 0.6931471805599454)
-2.0
[[2 3]
 [1 1]]
-1.0
[[2 3]
 [1 1]]
-1.0
[[2 2]
 [1 1]]
0.0
-2.0


In [6]:
# 역행렬 구하기

a = np.array([[1, 2], [3, 4]])
inv = np.linalg.inv(a)
print(a)
print(inv)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
