In [1]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = 5

print(a)
print(a * b)

[1 2 3 4 5]
[ 5 10 15 20 25]


In [2]:
b = np.arange(1, 4)
print(b)

[1 2 3]


In [6]:
import numpy as np

item_list = ['bolt', 'screw', 'nut', 'bracket']
x_coordinates = np.array([0.1, 1, 1.5, 2])
y_coordinates = np.array([2, 1, 0.2, 2])
z_coordinates = np.array([3, 1, 0.5, 4])
mass = np.array([3.50, 1.50, 0.79, 1.75])

x_location = np.dot(x_coordinates, mass) / sum(mass)
y_location = np.dot(y_coordinates, mass) / sum(mass)
z_location = np.dot(z_coordinates, mass) / sum(mass)

locations = np.array([x_location, y_location, z_location]).reshape(3, 1)
print(locations)

[[ 0.86671088]
 [ 1.61246684]
 [ 2.57228117]]


In [ ]:
import matplotlib.pyplot as plt

# 이전 결과를 그래프로 그리기!

In [11]:
a = np.random.randn(9).reshape((3, 3))
print(a)
print(a ** a)

[[ 0.50487303 -0.66533404 -1.45772002]
 [-0.02505508  1.7556062   0.14927369]
 [ 0.93093315  0.16428017  0.55427607]]
[[ 0.70818167         nan         nan]
 [        nan  2.68607258  0.7528309 ]
 [ 0.93554611  0.74325218  0.72103032]]


/Users/gyukebox/school/2-2/la/py/algebra-env/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in power
  This is separate from the ipykernel package so we can avoid doing imports until


In [13]:
a = np.arange(1, 10).reshape(3, 3)
print(a)
print(a ** 2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
