In [1]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = 5

print(a)
print(a * b)

[1 2 3 4 5]
[ 5 10 15 20 25]


In [2]:
b = np.arange(1, 4)
print(b)

[1 2 3]


In [ ]:
# coding: utf-8
a = np.mgrid[0:5]
print(a)
a = np.mgrid[0:5, 0:5]
a
a, b = np.mgrid[0:5]
a, b = np.mgrid[0:5, 0:5]
a
b
a * b
np.dot(a, b)
a += 1
a
b += 1
b
a * b
np.dot(a + b)
np.dot(a, b)