In [2]:
import numpy as np

a = np.array([2, 5, 7, 3, 1, 0, 1, 4, 5]).reshape((3, 3))
print(a)
print(np.linalg.det(a))

[[2 5 7]
 [3 1 0]
 [1 4 5]]
12.0


In [3]:
a = np.array([3, 5, 2, 4, 2, 3, -1, 2, 4]).reshape((3, 3))
print(a)
print(np.linalg.det(a))

[[ 3  5  2]
 [ 4  2  3]
 [-1  2  4]]
-69.0
